Add mobile aspect ratio option for videos
newrelic/gatsby-theme-newrelic pull request #691
Opened 2022-06-13 17:04 UTC by LizBaker

<img width="572" alt="Screen Shot 2022-06-13 at 10 01 38 AM" src="https://user-images.githubusercontent.com/39655074/173406930-2823290e-df1f-4e2f-9dc6-a6507d2200f0.png">

2022-06-13 18:20 UTC, clarkmcadoo submitted a review, later dismissed

2022-06-13 18:21 UTC, caylahamann reviewed
i'm not sure if we can do anything about this, but it appears that the control bar is a bit smaller for the vertical view (like in terms of height and font size) 

### Vertical
<img width="379" alt="Screen Shot 2022-06-13 at 2 20 02 PM" src="https://user-images.githubusercontent.com/38332422/173419102-e5216ce0-1e35-4ee9-9c95-e06893784bbe.png">

### Horizontal

<img width="534" alt="Screen Shot 2022-06-13 at 2 20 09 PM" src="https://user-images.githubusercontent.com/38332422/173419092-b503cc0b-e4ae-416e-b9a3-740f0676d440.png">

2022-06-13 20:16 UTC, LizBaker commented
> i'm not sure if we can do anything about this, but it appears that the control bar is a bit smaller for the vertical view (like in terms of height and font size)
> 
not seeing anything in my searches so far :[]

2022-06-14 18:24 UTC, roadlittledawn requested changes
Can we also update the package [README](https://github.com/newrelic/gatsby-theme-newrelic/blob/liz/aspect-ratio-video/packages/gatsby-theme-newrelic/README.md#video) for the additional prop / usage when it needs to be vertical?

2022-06-14 22:15 UTC, clarkmcadoo approved these changes

2022-06-14 22:15 UTC, merged