feat(components): skeleton
newrelic/gatsby-theme-newrelic pull request #701
Opened 2022-06-27 09:36 UTC by x8a

Added a skeleton component so we can use it with Split tests.

2022-06-28 13:19 UTC, caylahamann requested changes
Let me know if you have any questions about this feedback!!

2022-06-28 13:19 UTC, caylahamann commented on packages/gatsby-theme-newrelic/src/components/Skeleton.js
> +      @keyframes skeleton-loading {
this is looking great, one thing that still remains is to account for dark mode. We'll want to add styles for when the dark mode class name is applied to the page. It should look something like this: 
https://github.com/newrelic/gatsby-theme-newrelic/blob/e92c4259148b0349968629029f5a3cbaa41dce7f/packages/gatsby-theme-newrelic/src/components/TextHighlight.js#L25-L27

2022-06-28 13:19 UTC, caylahamann commented on demo/src/pages/index.js
>            <h2>Search inputs</h2>
small thing, but I notice that in the demo this breaks up the `SearchInput` section. You're going to want to move this `h2` to be right next to the `SearchInput`

2022-06-29 14:40 UTC, caylahamann approved these changes
This looks great!!! thanks for making those changes

2022-06-30 09:50 UTC, x8a commented
@roadlittledawn, thanks for the notes! I added those 💃🏻.

2022-06-30 16:27 UTC, merged